// <auto-generated />
namespace Book.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class field_book_year : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(field_book_year));
        
        string IMigrationMetadata.Id
        {
            get { return "202108211654123_field_book_year"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
