// <auto-generated />
namespace Book.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class book_rename_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(book_rename_field));
        
        string IMigrationMetadata.Id
        {
            get { return "202108211722563_book_rename_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
